aws-greengrass/aws-greengrass-testing

aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/LoggerSteps.java

otf-null is presented during IDT run; 
The version number for OTF is backed into the Standalone jar's Manifest. 
When customer is consuming the jar in their dependencies, they have to make changes in config to backed the version into their jar. 
This change is to set a default value to OTF version

fix: fix IDT version

---

.github/workflows/ci.yml

UAT is failed for forked PRs and it should be skipped.
Skip UAT run for external PRs
Tested by creating a PR from forked repository:
https://github.com/aws-greengrass/aws-greengrass-testing/pull/182

chore: skip uat-linux workflow for external PRs

---

aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/DeploymentSteps.java
aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/test/java/com.aws.greengrass.testing/features/DeploymentStepsTest.java

Add this step since LogManager and ShadowManager need to install custom components for UATs. Therefore, this step is is for the local deployment of custom components with configuration and recipes. 

feat: add steps for local deployment with configs

---

aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/DeploymentSteps.java
aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/test/java/com.aws.greengrass.testing/features/DeploymentStepsTest.java

- Remove command and path that incompatible with windows. 

fix: do not use Path for local store recipes

---

.github/workflows/ci.yml
aws-greengrass-testing-api/src/test/java/com/aws/greengrass/testing/api/ScenarioTestRunsTest.java

Add a workflow to scan secret by using [git-secret](https://github.com/awslabs/git-secrets). 
Tested by manually committed aws credential:  https://github.com/aws-greengrass/aws-greengrass-testing/actions/runs/4010787721/jobs/6887677326

chore: add secret scan workflow

---

README.md
aws-greengrass-testing-api/src/main/java/com/aws/greengrass/testing/api/device/local/LocalDevice.java
aws-greengrass-testing-standalone/README.md

Integration test and uat local runs for Windows devices are not working as expected.
~~~
com.aws.greengrass.testing.api.device.exception.CommandExecutionException: java.io.IOException: Cannot run program "cmd.exe /c": CreateProcess error=2, The system cannot find the file specified
~~~
1. In [LocalDevice.java](https://github.com/aws-greengrass/aws-greengrass-testing/compare/fixWindowsLocalTests?expand=1&short_path=b335630#diff-410e8fa2128318300c8f49bc72581f20d4956a83f0346dd2a978b54ef764e288), append "cmd.exe" and "/c" separately to ProcessBuilder;
2. Update README with detailed instructions on how to run tests on Windows device
Run below tests in both Linux and Windows …

fix: integration test and uat local runs for Windows devices

---

.github/scripts/binaryCompatibility.py
.github/workflows/ci.yml
pom.xml

Use [japicmp](https://github.com/siom79/japicmp) (Apache-2 licensed) to identify binary incompatible changes between pull request base and new changes; 
The workflow will: 
1. Check out the pull request base and install it to local maven repository. 
2. Checkout the pull request head, build it and compare the build artifact with 1.
3. Using a Python script it will comment our your PR if there are any incompatibilities. 
Tested by creating a PR that is breaking binary compatibility: https://github.com/aws-greengrass/aws-greengrass-testing/pull/189
Can see the notification message as: 
~~~
Binary incompatibility detected for commit …

chore: add workflow to check binary compatibility

---

aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/GreengrassCliSteps.java

Sometimes, GG throws access denied exceptions such as the following, when Greengrass local cli command is run.
```
Error: 1.295 [otf-1.1.0-SNAPSHOT] [] [gg-923baeaa8de3ef55836b] [ERROR] greengrass/features/log-manager-1.feature - Failed at step: 'the local Greengrass deployment is SUCCEEDED on the device after 180 seconds'
com.aws.greengrass.testing.api.device.exception.CommandExecutionException: May 30, 2023 11:40:50 PM software.amazon.awssdk.eventstreamrpc.EventStreamRPCConnection$1 onProtocolMessage
WARNING: AccessDenied to event stream RPC server
java.lang.RuntimeException: Unable to create ipc client
at com.aws.greengrass.cli.adapter.impl.NucleusAdapterIpcClientImpl.getIpcClient(NucleusAdapterIpcClientImpl.java:490)
```
This …

fix: retry gg local cli deployment status command in case of exceptions

---

aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/FileSteps.java

When multiple scenarios are tested in a single run, the logs of each test scenario as overridden by the last one. This change creates individual folders for each of the scenarios separately, and copy the corresponding logs from tests into those folders. 

fix: create test case folders in the test results

---

aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/DefaultGreengrass.java
aws-greengrass-testing-platform/aws-greengrass-testing-platform-api/src/main/java/com/aws/greengrass/testing/platform/Commands.java
aws-greengrass-testing-platform/aws-greengrass-testing-platform-api/src/main/java/com/aws/greengrass/testing/platform/UnixCommands.java
aws-greengrass-testing-platform/aws-greengrass-testing-platform-api/src/main/java/com/aws/greengrass/testing/platform/windows/WindowsCommands.java

Add sigterm command and uses it when stopping Greengrass rather than sigkill which will not give Greengrass time to properly shutdown and cleanup.

fix: gracefully stop Nucleus instead of killing

---

aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/RegistrationSteps.java
aws-greengrass-testing-resources/aws-greengrass-testing-resources-greengrass/src/main/java/com/aws/greengrass/testing/resources/greengrass/GreengrassCoreDeviceModel.java
aws-greengrass-testing-resources/aws-greengrass-testing-resources-greengrass/src/main/java/com/aws/greengrass/testing/resources/greengrass/GreengrassCoreDeviceSpecModel.java
aws-greengrass-testing-resources/aws-greengrass-testing-resources-greengrass/src/main/java/com/aws/greengrass/testing/resources/greengrass/GreengrassDeploymentModel.java
aws-greengrass-testing-resources/aws-greengrass-testing-resources-greengrass/src/main/java/com/aws/greengrass/testing/resources/greengrass/GreengrassV2Lifecycle.java

Currently the core device is only deleted if there's a deployment associated with it. This change now has us always attempt to delete the core device which we assume that we created when creating the iot thing.
This change also deletes the deployment instead of just canceling it.

fix: cleanup core device and deployments after testing

---

aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/RegistrationSteps.java
aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/util/EncryptionUtils.java
aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/test/java/com.aws.greengrass.testing/features/RegistrationStepsTest.java

Poll the IoT Credential endpoint until credentials are retrievable for the thing and role alias. This way when Greengrass starts up, we can immediately deploy to it and know that it will be running with valid credentials, removing some flakiness.
Validated results in this PR that OTF prints that it cannot assume the role once or twice, then prints that it was successful as expected.

fix: poll for iot role alias to exist

---

aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/FileSteps.java
aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/GreengrassCliSteps.java
aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/test/java/com.aws.greengrass.testing/features/GreengrassCliStepsTest.java

- Extend FileSteps to be able waiting for at least N occurrences of string in file
- tune verifyLocalDeployment() by receive time units
When Nucleus is restarted we need to check Bridge is connected to a local broker before continue but that report to log files event second time.
verifyLocalDeployment at the moment differs from other deployment waiting step by accept only seconds instead of time units
By using in scenarios

feat(features-api): extend FileSteps and tune GreengrassCliSteps

---

aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/component/LocalComponentPreparationService.java
aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/component/PreparationServiceUtils.java
aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/component/RecipeComponentPreparationService.java
aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/test/java/com.aws.greengrass.testing/component/LocalComponentPreparationServiceTest.java
aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/test/java/com.aws.greengrass.testing/component/RecipeComponentPreparationServiceTest.java
aws-greengrass-testing-features/aws-greengrass-testing-features-cloudcomponent/src/main/resources/greengrass/components/recipes/hello_world_recipe_multiplatform.yaml
aws-greengrass-testing-features/aws-greengrass-testing-features-cloudcomponent/src/main/resources/greengrass/features/cloudComponent.feature
aws-greengrass-testing-features/aws-greengrass-testing-features-localdeployment/src/main/resources/greengrass/components/recipes/local_hello_world_multiplatform.yaml
aws-greengrass-testing-features/aws-greengrass-testing-features-localdeployment/src/main/resources/greengrass/features/localdeployment.feature

#209 
- Fix bug with Mandatory Artifacts in Manifests item
- Fixed bug with invalid split for Windows files in LocalComponentPreparationService
- Update LocalComponentPreparationService by adding check artifacts of types file or classpath is exists and filter out Manifests if contains missing artifacts
- Update RecipeComponentPreparationService by adding check artifacts of types file or classpath is exists and filter out Manifests if contains missing artifacts
- Add PreparationServiceUtils with isArtifactExists()
- Update unit tests to mirror changes
- Add components and scenarios for Cloud and Local component tests
We can't use recipe files with contains Platform selectors inside Manifests.
It …

feat: add support for multi-platform manifests

---

aws-greengrass-testing-platform/aws-greengrass-testing-platform-api/src/main/java/com/aws/greengrass/testing/platform/NetworkUtils.java
aws-greengrass-testing-platform/aws-greengrass-testing-platform-api/src/main/java/com/aws/greengrass/testing/platform/linux/LinuxNetworkUtils.java

None. Has request to remove port 443 from post of blocked port of NetworkUtils.disconnectMqtt()
- Remove port 443 from the list of ports to block
- Add javadoc to describe what is doing here
I do not know for sure
Not tested due to first should delivery changes to maven repo

fix: remove 443 from list of blocked ports

---

aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/NetworkUtilsSteps.java
aws-greengrass-testing-platform/aws-greengrass-testing-platform-api/src/main/java/com/aws/greengrass/testing/platform/linux/LinuxNetworkUtils.java

OTF Step to add IP address to lo interface is not automatically reverted
- Add rollback of changes in list of IP addresses assigned to lo interface
- Replace 127.0.0.1 to localhost in iptables rules
When step "I remove IP address" is missed in scenario or when skipped due to failure in some other step assigned IP addresses kept for lo interface. That can cause other scenarios to fail.

fix: add rollback of changes in list of IP addresses assigned to lo interface

---

aws-greengrass-testing-features/aws-greengrass-testing-features-docker/src/main/java/com/aws/greengrass/testing/features/DockerSteps.java

Docker image cleanup will fail if the image doesn't exist. Catch the exception, log it and then keep going. This should not cause any tests to fail.

fix(docker): do not fail docker image cleanup

---

aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/DeploymentSteps.java
aws-greengrass-testing-features/aws-greengrass-testing-features-cloudcomponent/src/main/resources/greengrass/features/cloudComponent.feature

#207 
- Add CURRENT keyword as version of component to resolve #207 
- Add scenario to test new feature
Without that change we have an issue when do secondary deployment with the same classpath or localstore component
Automatically on CI by run new scenario

feat: use CURRENT keyword as version of already deployed component

---

pom.xml

- Bump the AWS SDK version to latest. 
- Use [`versions-maven-plugin`](https://www.mojohaus.org/versions/versions-maven-plugin/update-properties-mojo.html) to identify and update the aws java sdk version to latest in the pom.xml file using `update-properties` goal. 
- This plugin automatically updates the sdk version in the pom.xml when the project is built locally (using `mvn install`). Developers have to still commit the changes. 
- If the SDK version in the pom.xml is not the latest one available, the GitHub workflow fails (as it tries to update the pom.xml but fails as it doesn't have the permissions to update the file). If there's no update, the build step completes successfully. 
**How was this …

chore: update aws sdk dependency

---

aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/GreengrassCliSteps.java
aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/NetworkUtilsSteps.java
aws-greengrass-testing-platform/aws-greengrass-testing-platform-api/src/main/java/com/aws/greengrass/testing/platform/NetworkUtils.java
aws-greengrass-testing-platform/aws-greengrass-testing-platform-api/src/main/java/com/aws/greengrass/testing/platform/linux/LinuxNetworkUtils.java
aws-greengrass-testing-platform/aws-greengrass-testing-platform-api/src/main/java/com/aws/greengrass/testing/platform/macos/MacosNetworkUtils.java
aws-greengrass-testing-platform/aws-greengrass-testing-platform-api/src/main/java/com/aws/greengrass/testing/platform/macos/MacosPlatform.java
aws-greengrass-testing-platform/aws-greengrass-testing-platform-api/src/main/java/com/aws/greengrass/testing/platform/windows/WindowsNetworkUtils.java
pom.xml

Steps to set device network to offline and online.
Platform specific (Linux and MacOS) commands to run these steps.
To support confidence tests introduced in component template repo
PR: https://github.com/aws-greengrass/aws-greengrass-component-templates/pull/40
Tested locally on MacOS and used EC2 instances for testing Linux changes.

feat: add step and platform commands for device network

---

aws-greengrass-testing-components/aws-greengrass-testing-components-ggipc/pom.xml
aws-greengrass-testing-examples/aws-greengrass-testing-examples-component/pom.xml
aws-greengrass-testing-features/aws-greengrass-testing-features-mqtt/pom.xml

Add jackson-core to the pom.xml for aws-greengrass-testing-examples-component. This is placed above the iotdevicesdk dependency which will otherwise create a dependency on jackson 2.12.0 which conflicts with the version of jackson we do want.
When running the existing tests, I would always get a NoSuchMethodError for aws-greengrass-testing-examples-component. This is due to iotdevicesdk jar taking on a transitive dependency on jackson 2.12.0, which in turn excludes the 2.15.2 version of jackson that the project is actually trying to use as there is a conflict. This results in the NoSuchMethodError as the wrong jackson version is being used.
The tests that were …

fix: enforce jackson version dependency to exclude correct duplicate

---

CHANGELOG.md

Update the changelog with v1.2.0 improvements.
Keep changelog updated
N/A

chore: update changelog with 1.2.0 updates

---

aws-greengrass-testing-components/aws-greengrass-testing-components-streammanager/recipe.yaml
aws-greengrass-testing-examples/aws-greengrass-testing-examples-component/README.md
aws-greengrass-testing-examples/aws-greengrass-testing-examples-component/recipe.yaml
aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/LoggerSteps.java
pom.xml

Bump versions to 1.3.0-SNAPSHOT in all relevant places.
1.2.0 is released, so we want the current main branch to track 1.3.0-SNAPSHOT.
N/A

chore: bump minor version number to 1.3.0-SNAPSHOT in relevant places

---

aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/DeploymentSteps.java
aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/GreengrassCliSteps.java
aws-greengrass-testing-features/aws-greengrass-testing-features-cloudcomponent/src/main/resources/greengrass/components/recipes/hello_world_recipe_multiplatform.yaml
aws-greengrass-testing-features/aws-greengrass-testing-features-localdeployment/src/main/resources/greengrass/components/recipes/local_hello_world_multiplatform.yaml

Do not attempt to upload /bin/bash or cmd as a recipe artifact.

fix(idt): remove cmd and bash requirements

---

aws-greengrass-testing-features/aws-greengrass-testing-features-cloudcomponent/src/main/resources/greengrass/features/cloudComponent.feature
aws-greengrass-testing-features/aws-greengrass-testing-features-localdeployment/src/main/resources/greengrass/features/localdeployment.feature

P123929293
Disable multi-platform component feature tests when running in IDT
These tests are not necessary for IDT
n/a

chore: remove IDT tag from multiplatform component feature tests

---

.github/workflows/ci.yml

ci: upgrade github actions

---

aws-greengrass-testing-features/aws-greengrass-testing-features-localdeployment/src/main/resources/greengrass/features/localdeployment.feature

test: remove IDT tag from local deployment test

---

components/BrokenAfterDeployed/1.0.0/artifacts/broken_after_deployed.py
components/BrokenAfterDeployed/1.0.0/recipe/BrokenAfterDeployed-1.0.0.yaml
pyproject.toml
src/GGTestUtils.py
src/aws-greengrass-testing-fleet-status.py

```
(env) ubuntu@ip-172-31-87-177:~/repo/aws-greengrass-testing$ pytest -q -s -v  -k "test_FleetStatus_1_T3"
====================================================================================================================================== test session starts =======================================================================================================================================
platform linux -- Python 3.12.3, pytest-8.3.5, pluggy-1.5.0
rootdir: /home/ubuntu/repo/aws-greengrass-testing
configfile: pyproject.toml
testpaths: ./src/*
collected 18 items / 17 deselected / 1 selected …
```

Add the test_FleetStatus_1_T3

---

.github/scripts/binaryCompatibility.py
.github/scripts/cover2cover.py
config/config.py
src/GGTestUtils.py
src/SystemInterface.py
src/aws-greengrass-testing-component.py
src/aws-greengrass-testing-deployment.py
src/aws-greengrass-testing-fleet-status.py
src/aws-greengrass-testing-security.py

- This PR will extend cloud create deployment enabling merge config values for generic components
- Format files as per the formatting guidelines
- Adds a partially complete security test

Extend cloud create deployment enabling merge config values

---

components/HelloWorldBroken/1.0.0/recipe/HelloWorldBroken-1.0.0.yaml
components/Minimal/1.0.0/recipe/Minimal-1.0.0.yaml
components/Minimal/2.0.0/recipe/Minimal-2.0.0.yaml
components/Minimal/3.0.0/recipe/Minimal-3.0.0.yaml
components/Minimal/4.0.0/recipe/Minimal-4.0.0.yaml
components/SampleComponentWithArtifacts/1.0.0/artifacts/sample_artifact.py
components/aws.gg.uat.cloud.ComponentConfigTestService/1.0.0/recipe/aws.gg.uat.cloud.ComponentConfigTestService-1.0.0.yaml
components/aws.gg.uat.local.ComponentConfigTestService/1.0.0/recipe/aws.gg.uat.local.ComponentConfigTestService-1.0.0.yaml
components/local_artifacts/SampleComponentWithArtifacts/1.0.0/sample_artifact.py
components/local_artifacts/aws.gg.uat.local.ComponentConfigTestService/1.0.0/print_json_env.py
config/config.py
src/GGTestUtils.py
src/SystemInterface.py
src/aws-greengrass-testing-component.py
src/aws-greengrass-testing-deployment.py
src/aws-greengrass-testing-fleet-status.py
src/aws-greengrass-testing-security.py

Adds Deployment-1-T6, Deployment-1-T12, Component-29-T0, Component-29-T4, and Component-34-T4.
Note that because local deployments requires a specific structure for the artifacts directory, there is a new local_artifacts folder that stores artifacts for local deployments rather than keeping them in their respective component directory. Eventually we may want to rethink our component directory structure.
Currently, Component-29-T0 and Component-29-T4 due possible bugs in GGL regarding handling recipe variable substitution when a configuration does not exist, and escaping quotes when adding to env variables. 
Add new tests
The tests all pass except for Component-29-T0 and …

Add new component and deployment tests

---

src/IoTUtils.py
src/aws-greengrass-testing-component.py
src/aws-greengrass-testing-deployment.py
src/aws-greengrass-testing-fleet-status.py
src/aws-greengrass-testing-runtime.py
src/aws-greengrass-testing-security.py

Updated all test files to accommodate modifications introduced in the previous pull request.
Have tested 5 files locally, and all test cases are passed.
To test locally:
./run-tests.sh --aws-account=<account> --s3-bucket=<bucket_name> --commit-id=<id_num> --aws-region=<region> --test-category=<e.g. security/deployment/runtime/fleet-status/component>

Updated all test cases
