aws-greengrass/aws-greengrass-testing

- aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/DeploymentSteps.java
Use Json file path as `--update-config` argument value in the local cli deployment create command instead of a string. 
This is compatible on both windows and linux where JSON Strings passed in the config need not be formatted to fit specific platform. 
> refactor: use file instead of string as cli update config arg

- aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/DeploymentSteps.java
- Refactor code to add local deployment update step. 
- Currently, local deployment installment steps can deploy only one component at a time. 
> refactor: add local deployment update step

- .github/workflows/ci.yml
Add workflow to build otf on windows
> chore: add build workflow on windows

- aws-greengrass-testing-components/aws-greengrass-testing-components-streammanager/recipe.yaml
- aws-greengrass-testing-examples/aws-greengrass-testing-examples-component/README.md
- aws-greengrass-testing-examples/aws-greengrass-testing-examples-component/recipe.yaml
- aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/LoggerSteps.java
- pom.xml
update version to 1.1.0-SNAPSHOT following MCM
mvn clean && mvn package
> chore: update version to 1.1.0-SNAPSHOT

- CHANGELOG.md
> chore: update changelog for v1.1.0 release 

- aws-greengrass-testing-components/aws-greengrass-testing-components-streammanager/recipe.yaml
- aws-greengrass-testing-examples/aws-greengrass-testing-examples-component/README.md
- aws-greengrass-testing-examples/aws-greengrass-testing-examples-component/recipe.yaml
- aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/LoggerSteps.java
- pom.xml
update version to 1.2.0 as part of 1.1.0 release MCM
> chore: update version to 1.2.0

- aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/NetworkUtilsSteps.java
- Add NetworkUtilsSteps with steps to disable and enable MQTT connections
To implement test cases when new configuration is applied when MQTT connectivity is disabled
By run pending scenario outlines
> feat: add NetworkUtilsSteps

- aws-greengrass-testing-features/aws-greengrass-testing-features-api/src/main/java/com/aws/greengrass/testing/features/NetworkUtilsSteps.java
- aws-greengrass-testing-platform/aws-greengrass-testing-platform-api/src/main/java/com/aws/greengrass/testing/platform/NetworkUtils.java
- aws-greengrass-testing-platform/aws-greengrass-testing-platform-api/src/main/java/com/aws/greengrass/testing/platform/linux/LinuxNetworkUtils.java
- aws-greengrass-testing-platform/aws-greengrass-testing-platform-api/src/main/java/com/aws/greengrass/testing/platform/macos/MacosNetworkUtils.java
- aws-greengrass-testing-platform/aws-greengrass-testing-platform-api/src/main/java/com/aws/greengrass/testing/platform/windows/WindowsNetworkUtils.java
add and remove steps for loopback address
- Add 'I add IP address "ip_address" to loopback interface' step
- Add 'I remove IP address "ip_address" from loopback interface' step
Implement scenarios
Run scenario on CodeBuild
**Test results:**
```
Given my device is registered as a Thing....................................passed
And my device is running Greengrass.........................................passed
When I create a Greengrass deployment with components.......................passed
And I create client device "basic_connect"..................................passed
When I associate "basic_connect" with ggc...................................passed
And I update my …
```
> feat(uat): add and remove steps for loopback address

- aws-greengrass-testing-platform/aws-greengrass-testing-platform-api/src/main/java/com/aws/greengrass/testing/platform/windows/WindowsNetworkUtils.java
Windows firewall rules are creates with the same name
-  Update WindowsNetworkUtils to generate unique rule names
When rule name as duplicate Windows netsh advfirewall command overwrite rule with the same name but in other direction.
It resulting rules do not block MQTT connections at all.
When run T17, T18 and T27 scenarios on Windows.
Problem comes from evergreen. Be careful it has the same bug.
> fix(platform): resolve duplicated rule name conflict

- aws-greengrass-testing-platform/aws-greengrass-testing-platform-api/src/main/java/com/aws/greengrass/testing/platform/windows/WindowsNetworkUtils.java
- pom.xml
Windows specific commands to connect and disconnect internet.
To support confidence test running on Windows Platform.
Tested locally on Windows EC2 instance.
> feat: Windows specific network commands

- aws-greengrass-testing-features/aws-greengrass-testing-features-ml/src/main/resources/greengrass/features/ml.feature
- aws-greengrass-testing-features/aws-greengrass-testing-features-streammanager/src/main/resources/greengrass/features/streammanager.feature
> chore: remove IDT tag from ML and streammanager tests

- components/Component2BaseCloud/1.0.0/recipe/Component2BaseCloud-1.0.0.yaml
- conftest.py
It also adds the recipe for Component2BaseCloud-1.0.0.yaml for later use.
> Add parameter checking

- components/SampleComponentWithArtifacts/1.0.0/recipe/SampleComponentWithArtifacts-1.0.0.yaml
- components/SampleComponentWithConfiguration/1.0.0/recipe/SampleComponentWithConfiguration-1.0.0.yaml
- config/config.py
- src/GGTestUtils.py
- src/IoTUtils.py
- src/aws-greengrass-testing-component.py
- src/aws-greengrass-testing-deployment.py
- src/aws-greengrass-testing-fleet-status.py
> Add tests Deployment_7_T4 and Deployment_7_T3

- pyproject.toml
- src/GGTestUtils.py
- src/IoTUtils.py
- src/SystemInterface.py
- src/aws-greengrass-testing-component.py
- src/aws-greengrass-testing-deployment.py
- src/aws-greengrass-testing-fleet-status.py
- uv.lock
* Add types-boto3 to uv
* Add type hints to test functions
Allows language server auto-completions on test objects and boto3 objects
> Add type hints to test utils and boto3 usage

- .gitignore
- src/GGTestUtils.py
> Check the component length to avoid the tuple index out of range

- misc/recipe_template.yaml
- src/GGTestUtils.py
- src/IoTUtils.py
- src/aws-greengrass-testing-deployment.py
- src/aws-greengrass-testing-fleet-status.py
> Add tests test_Deployment_8_T3 and test_Deployment_8_T2

- components/HelloWorldPubSub/1.0.0/artifacts/hello_world_pub_sub.py
- components/HelloWorldPubSub/1.0.0/recipe/HelloWorldPubSub-1.0.0.yaml
- src/GGTestUtils.py
- src/aws-greengrass-testing-security.py
> Add Pubsub Security Testing

- components/DependsHelloWorldA/1.0.0/recipe/DependsHelloWorldA-1.0.0.yaml
- components/DependsHelloWorldB/1.0.0/recipe/DependsHelloWorldB-1.0.0.yaml
- components/HelloWorldPubSub/1.0.0/artifacts/hello_world_pub_sub.py
- components/HelloWorldPubSub/1.0.0/recipe/HelloWorldPubSub-1.0.0.yaml
- src/GGTestUtils.py
- src/aws-greengrass-testing-component.py
- src/aws-greengrass-testing-deployment.py
- src/aws-greengrass-testing-fleet-status.py
- src/aws-greengrass-testing-security.py
> Add test_Deployment_8_T5 and fix bugs in tests

- components/Component2BaseCloud/1.0.0/recipe/Component2BaseCloud-1.0.0.yaml
- components/component_with_soft_dep/1.0.0/recipe/broken_soft_dep-1.0.0.yaml
- components/component_with_soft_dep/1.0.0/recipe/component_with_soft_dep-1.0.0.yaml
- src/SystemInterface.py
- src/aws-greengrasstesting-runtime.py
> Add test_Runtime_1_T9 and test_Runtime_25_T1

- components/process_status_component_privilege/0.0.0/recipe/process_status_component_privilege-0.0.0.yaml
- src/SystemInterface.py
- src/aws-greengrasstesting-runtime.py
> Add test test_Runtime_28_T3

- components/HelloWorldMqtt/1.0.0/artifacts/hello_world_mqtt.py
- components/HelloWorldMqtt/1.0.0/recipe/HelloWorldMqtt-1.0.0.yaml
- components/HelloWorldPubSub/1.0.0/recipe/HelloWorldPubSub-1.0.0.yaml
- pyproject.toml
- src/aws-greengrass-testing-security.py
- uv.lock
* Add awsiotsdk to dependencies
* Add mqtt security tests
> Add MQTT Security Testing

- components/HelloWorldMqtt/1.0.0/recipe/HelloWorldMqtt-1.0.0.yaml
- config/config.py
- src/GGTestUtils.py
- src/IoTUtils.py
- src/aws-greengrass-testing-component.py
- src/aws-greengrass-testing-deployment.py
- src/aws-greengrass-testing-fleet-status.py
- src/aws-greengrass-testing-security.py
- src/aws-greengrasstesting-runtime.py
> Clean up code and retry API calls on failure

- tools/cloud_deployment_cleanup/README.md
- tools/cloud_deployment_cleanup/cloud_deployment_cleanup.sh
> Add cloud deployment cleanup Script

- conftest.py
- run-tests.sh
- src/GGLSetup.py
- src/IoTUtils.py
- src/aws-greengrass-testing-deployment.py
Modify IoTUtils to enable boto3 client reuse. 
Additional test file modifications will be handled in a separate PR.
> Refactor IoTUtils for deployment tests

- src/SystemInterface.py
> Print the journalctl output

- run-tests.sh
- src/SystemInterface.py
- tools/cloud_deployment_cleanup/README.md
- tools/cloud_deployment_cleanup/cloud_deployment_cleanup.sh
> Dup deployment remove

- src/GGLSetup.py
> Fix typo in GGL setup
